[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "placeholder_name"
version = "0"
description = "As we progress along the datascience branch of 42Paris School, we are building this toolkit"
authors = [
    { name = "ybendavi", email = "ybendavi@student.42.fr" },
    { name = "ccottin", email = "ccottin@student.42.fr" },
]
requires-python = ">=3.12"
dependencies = [
    "pandas",
    ]